services:
  - type: web
    name: whatsapp-fetcher
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn whatsapp_message_fetcher:app --host 0.0.0.0 --port 8000"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: INFOBIP_API_KEY
        sync: false
      - key: INFOBIP_BASE_URL
        sync: false
      - key: WHATSAPP_SENDER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SHOPIFY_SHOP_DOMAIN
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_WEBHOOK_SECRET
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false 
      - key: SECRET_KEY
        generateValue: true
        generateValue: true